/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface ForwarderInterface extends utils.Interface {
  functions: {
    "computeAddress(address)": FunctionFragment;
    "execute(address,address[],bytes[],uint256[],bytes,uint256,uint256)": FunctionFragment;
    "gswFactory()": FunctionFragment;
    "gswNonce(address)": FunctionFragment;
    "verify(address,address[],bytes[],uint256[],bytes,uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "computeAddress"
      | "execute"
      | "gswFactory"
      | "gswNonce"
      | "verify"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "computeAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "gswFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gswNonce",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "computeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gswFactory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gswNonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {};
}

export interface Forwarder extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ForwarderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    computeAddress(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    execute(
      from: PromiseOrValue<string>,
      targets: PromiseOrValue<string>[],
      datas: PromiseOrValue<BytesLike>[],
      values: PromiseOrValue<BigNumberish>[],
      signature: PromiseOrValue<BytesLike>,
      validUntil: PromiseOrValue<BigNumberish>,
      gas: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    gswFactory(overrides?: CallOverrides): Promise<[string]>;

    gswNonce(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    verify(
      from: PromiseOrValue<string>,
      targets: PromiseOrValue<string>[],
      datas: PromiseOrValue<BytesLike>[],
      values: PromiseOrValue<BigNumberish>[],
      signature: PromiseOrValue<BytesLike>,
      validUntil: PromiseOrValue<BigNumberish>,
      gas: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  computeAddress(
    owner: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  execute(
    from: PromiseOrValue<string>,
    targets: PromiseOrValue<string>[],
    datas: PromiseOrValue<BytesLike>[],
    values: PromiseOrValue<BigNumberish>[],
    signature: PromiseOrValue<BytesLike>,
    validUntil: PromiseOrValue<BigNumberish>,
    gas: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  gswFactory(overrides?: CallOverrides): Promise<string>;

  gswNonce(
    owner: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  verify(
    from: PromiseOrValue<string>,
    targets: PromiseOrValue<string>[],
    datas: PromiseOrValue<BytesLike>[],
    values: PromiseOrValue<BigNumberish>[],
    signature: PromiseOrValue<BytesLike>,
    validUntil: PromiseOrValue<BigNumberish>,
    gas: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    computeAddress(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    execute(
      from: PromiseOrValue<string>,
      targets: PromiseOrValue<string>[],
      datas: PromiseOrValue<BytesLike>[],
      values: PromiseOrValue<BigNumberish>[],
      signature: PromiseOrValue<BytesLike>,
      validUntil: PromiseOrValue<BigNumberish>,
      gas: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    gswFactory(overrides?: CallOverrides): Promise<string>;

    gswNonce(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verify(
      from: PromiseOrValue<string>,
      targets: PromiseOrValue<string>[],
      datas: PromiseOrValue<BytesLike>[],
      values: PromiseOrValue<BigNumberish>[],
      signature: PromiseOrValue<BytesLike>,
      validUntil: PromiseOrValue<BigNumberish>,
      gas: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    computeAddress(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    execute(
      from: PromiseOrValue<string>,
      targets: PromiseOrValue<string>[],
      datas: PromiseOrValue<BytesLike>[],
      values: PromiseOrValue<BigNumberish>[],
      signature: PromiseOrValue<BytesLike>,
      validUntil: PromiseOrValue<BigNumberish>,
      gas: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    gswFactory(overrides?: CallOverrides): Promise<BigNumber>;

    gswNonce(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verify(
      from: PromiseOrValue<string>,
      targets: PromiseOrValue<string>[],
      datas: PromiseOrValue<BytesLike>[],
      values: PromiseOrValue<BigNumberish>[],
      signature: PromiseOrValue<BytesLike>,
      validUntil: PromiseOrValue<BigNumberish>,
      gas: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    computeAddress(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    execute(
      from: PromiseOrValue<string>,
      targets: PromiseOrValue<string>[],
      datas: PromiseOrValue<BytesLike>[],
      values: PromiseOrValue<BigNumberish>[],
      signature: PromiseOrValue<BytesLike>,
      validUntil: PromiseOrValue<BigNumberish>,
      gas: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    gswFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gswNonce(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verify(
      from: PromiseOrValue<string>,
      targets: PromiseOrValue<string>[],
      datas: PromiseOrValue<BytesLike>[],
      values: PromiseOrValue<BigNumberish>[],
      signature: PromiseOrValue<BytesLike>,
      validUntil: PromiseOrValue<BigNumberish>,
      gas: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
