/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace AvocadoMultisigStructs {
  export type ActionStruct = {
    target: PromiseOrValue<string>;
    data: PromiseOrValue<BytesLike>;
    value: PromiseOrValue<BigNumberish>;
    operation: PromiseOrValue<BigNumberish>;
  };

  export type ActionStructOutput = [string, string, BigNumber, BigNumber] & {
    target: string;
    data: string;
    value: BigNumber;
    operation: BigNumber;
  };

  export type CastParamsStruct = {
    actions: AvocadoMultisigStructs.ActionStruct[];
    id: PromiseOrValue<BigNumberish>;
    avoNonce: PromiseOrValue<BigNumberish>;
    salt: PromiseOrValue<BytesLike>;
    source: PromiseOrValue<string>;
    metadata: PromiseOrValue<BytesLike>;
  };

  export type CastParamsStructOutput = [
    AvocadoMultisigStructs.ActionStructOutput[],
    BigNumber,
    BigNumber,
    string,
    string,
    string
  ] & {
    actions: AvocadoMultisigStructs.ActionStructOutput[];
    id: BigNumber;
    avoNonce: BigNumber;
    salt: string;
    source: string;
    metadata: string;
  };

  export type CastForwardParamsStruct = {
    gas: PromiseOrValue<BigNumberish>;
    gasPrice: PromiseOrValue<BigNumberish>;
    validAfter: PromiseOrValue<BigNumberish>;
    validUntil: PromiseOrValue<BigNumberish>;
    value: PromiseOrValue<BigNumberish>;
  };

  export type CastForwardParamsStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    gas: BigNumber;
    gasPrice: BigNumber;
    validAfter: BigNumber;
    validUntil: BigNumber;
    value: BigNumber;
  };

  export type SignatureParamsStruct = {
    signature: PromiseOrValue<BytesLike>;
    signer: PromiseOrValue<string>;
  };

  export type SignatureParamsStructOutput = [string, string] & {
    signature: string;
    signer: string;
  };
}

export declare namespace AvoForwarderStructs {
  export type AddressBoolStruct = {
    addr: PromiseOrValue<string>;
    value: PromiseOrValue<boolean>;
  };

  export type AddressBoolStructOutput = [string, boolean] & {
    addr: string;
    value: boolean;
  };
}

export interface MultisigForwarderInterface extends utils.Interface {
  functions: {
    "avoFactory()": FunctionFragment;
    "avoNonce(address,uint32)": FunctionFragment;
    "avocadoBytecode()": FunctionFragment;
    "avocadoVersion(address,uint32)": FunctionFragment;
    "avocadoVersionName(address,uint32)": FunctionFragment;
    "computeAvocado(address,uint32)": FunctionFragment;
    "executeV1(address,uint32,((address,bytes,uint256,uint256)[],uint256,int256,bytes32,address,bytes),(uint256,uint256,uint256,uint256,uint256),(bytes,address)[])": FunctionFragment;
    "initialize(address,address[])": FunctionFragment;
    "isAuth(address)": FunctionFragment;
    "isBroadcaster(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "simulateV1(address,uint32,((address,bytes,uint256,uint256)[],uint256,int256,bytes32,address,bytes),(uint256,uint256,uint256,uint256,uint256),(bytes,address)[])": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateAuths((address,bool)[])": FunctionFragment;
    "updateBroadcasters((address,bool)[])": FunctionFragment;
    "verifyV1(address,uint32,((address,bytes,uint256,uint256)[],uint256,int256,bytes32,address,bytes),(uint256,uint256,uint256,uint256,uint256),(bytes,address)[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "avoFactory"
      | "avoNonce"
      | "avocadoBytecode"
      | "avocadoVersion"
      | "avocadoVersionName"
      | "computeAvocado"
      | "executeV1"
      | "initialize"
      | "isAuth"
      | "isBroadcaster"
      | "owner"
      | "renounceOwnership"
      | "simulateV1"
      | "transferOwnership"
      | "updateAuths"
      | "updateBroadcasters"
      | "verifyV1"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "avoFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "avoNonce",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "avocadoBytecode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "avocadoVersion",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "avocadoVersionName",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "computeAvocado",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "executeV1",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      AvocadoMultisigStructs.CastParamsStruct,
      AvocadoMultisigStructs.CastForwardParamsStruct,
      AvocadoMultisigStructs.SignatureParamsStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [PromiseOrValue<string>, PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuth",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isBroadcaster",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "simulateV1",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      AvocadoMultisigStructs.CastParamsStruct,
      AvocadoMultisigStructs.CastForwardParamsStruct,
      AvocadoMultisigStructs.SignatureParamsStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAuths",
    values: [AvoForwarderStructs.AddressBoolStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBroadcasters",
    values: [AvoForwarderStructs.AddressBoolStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyV1",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      AvocadoMultisigStructs.CastParamsStruct,
      AvocadoMultisigStructs.CastForwardParamsStruct,
      AvocadoMultisigStructs.SignatureParamsStruct[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "avoFactory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "avoNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "avocadoBytecode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "avocadoVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "avocadoVersionName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeAvocado",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "executeV1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAuth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isBroadcaster",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "simulateV1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAuths",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBroadcasters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyV1", data: BytesLike): Result;

  events: {
    "AuthUpdated(address,bool)": EventFragment;
    "BroadcasterUpdated(address,bool)": EventFragment;
    "ExecuteFailed(address,uint32,address,address,bytes,string)": EventFragment;
    "Executed(address,uint32,address,address,bytes)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuthUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BroadcasterUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecuteFailed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Executed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface AuthUpdatedEventObject {
  auth: string;
  status: boolean;
}
export type AuthUpdatedEvent = TypedEvent<
  [string, boolean],
  AuthUpdatedEventObject
>;

export type AuthUpdatedEventFilter = TypedEventFilter<AuthUpdatedEvent>;

export interface BroadcasterUpdatedEventObject {
  broadcaster: string;
  status: boolean;
}
export type BroadcasterUpdatedEvent = TypedEvent<
  [string, boolean],
  BroadcasterUpdatedEventObject
>;

export type BroadcasterUpdatedEventFilter =
  TypedEventFilter<BroadcasterUpdatedEvent>;

export interface ExecuteFailedEventObject {
  avocadoOwner: string;
  index: number;
  avocadoAddress: string;
  source: string;
  metadata: string;
  reason: string;
}
export type ExecuteFailedEvent = TypedEvent<
  [string, number, string, string, string, string],
  ExecuteFailedEventObject
>;

export type ExecuteFailedEventFilter = TypedEventFilter<ExecuteFailedEvent>;

export interface ExecutedEventObject {
  avocadoOwner: string;
  index: number;
  avocadoAddress: string;
  source: string;
  metadata: string;
}
export type ExecutedEvent = TypedEvent<
  [string, number, string, string, string],
  ExecutedEventObject
>;

export type ExecutedEventFilter = TypedEventFilter<ExecutedEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface MultisigForwarder extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MultisigForwarderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    avoFactory(overrides?: CallOverrides): Promise<[string]>;

    avoNonce(
      owner_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    avocadoBytecode(overrides?: CallOverrides): Promise<[string]>;

    avocadoVersion(
      owner_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    avocadoVersionName(
      owner_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    computeAvocado(
      owner_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    executeV1(
      from_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      params_: AvocadoMultisigStructs.CastParamsStruct,
      forwardParams_: AvocadoMultisigStructs.CastForwardParamsStruct,
      signaturesParams_: AvocadoMultisigStructs.SignatureParamsStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initialize(
      owner_: PromiseOrValue<string>,
      allowedBroadcasters_: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isAuth(
      auth_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isBroadcaster(
      broadcaster_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(overrides?: CallOverrides): Promise<[void]>;

    simulateV1(
      from_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      params_: AvocadoMultisigStructs.CastParamsStruct,
      forwardParams_: AvocadoMultisigStructs.CastForwardParamsStruct,
      signaturesParams_: AvocadoMultisigStructs.SignatureParamsStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateAuths(
      authsStatus_: AvoForwarderStructs.AddressBoolStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateBroadcasters(
      broadcastersStatus_: AvoForwarderStructs.AddressBoolStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    verifyV1(
      from_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      params_: AvocadoMultisigStructs.CastParamsStruct,
      forwardParams_: AvocadoMultisigStructs.CastForwardParamsStruct,
      signaturesParams_: AvocadoMultisigStructs.SignatureParamsStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  avoFactory(overrides?: CallOverrides): Promise<string>;

  avoNonce(
    owner_: PromiseOrValue<string>,
    index_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  avocadoBytecode(overrides?: CallOverrides): Promise<string>;

  avocadoVersion(
    owner_: PromiseOrValue<string>,
    index_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  avocadoVersionName(
    owner_: PromiseOrValue<string>,
    index_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  computeAvocado(
    owner_: PromiseOrValue<string>,
    index_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  executeV1(
    from_: PromiseOrValue<string>,
    index_: PromiseOrValue<BigNumberish>,
    params_: AvocadoMultisigStructs.CastParamsStruct,
    forwardParams_: AvocadoMultisigStructs.CastForwardParamsStruct,
    signaturesParams_: AvocadoMultisigStructs.SignatureParamsStruct[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initialize(
    owner_: PromiseOrValue<string>,
    allowedBroadcasters_: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isAuth(
    auth_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isBroadcaster(
    broadcaster_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(overrides?: CallOverrides): Promise<void>;

  simulateV1(
    from_: PromiseOrValue<string>,
    index_: PromiseOrValue<BigNumberish>,
    params_: AvocadoMultisigStructs.CastParamsStruct,
    forwardParams_: AvocadoMultisigStructs.CastForwardParamsStruct,
    signaturesParams_: AvocadoMultisigStructs.SignatureParamsStruct[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateAuths(
    authsStatus_: AvoForwarderStructs.AddressBoolStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateBroadcasters(
    broadcastersStatus_: AvoForwarderStructs.AddressBoolStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  verifyV1(
    from_: PromiseOrValue<string>,
    index_: PromiseOrValue<BigNumberish>,
    params_: AvocadoMultisigStructs.CastParamsStruct,
    forwardParams_: AvocadoMultisigStructs.CastForwardParamsStruct,
    signaturesParams_: AvocadoMultisigStructs.SignatureParamsStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    avoFactory(overrides?: CallOverrides): Promise<string>;

    avoNonce(
      owner_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    avocadoBytecode(overrides?: CallOverrides): Promise<string>;

    avocadoVersion(
      owner_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    avocadoVersionName(
      owner_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    computeAvocado(
      owner_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    executeV1(
      from_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      params_: AvocadoMultisigStructs.CastParamsStruct,
      forwardParams_: AvocadoMultisigStructs.CastForwardParamsStruct,
      signaturesParams_: AvocadoMultisigStructs.SignatureParamsStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    initialize(
      owner_: PromiseOrValue<string>,
      allowedBroadcasters_: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    isAuth(
      auth_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isBroadcaster(
      broadcaster_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    simulateV1(
      from_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      params_: AvocadoMultisigStructs.CastParamsStruct,
      forwardParams_: AvocadoMultisigStructs.CastForwardParamsStruct,
      signaturesParams_: AvocadoMultisigStructs.SignatureParamsStruct[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean, boolean, string] & {
        castGasUsed_: BigNumber;
        deploymentGasUsed_: BigNumber;
        isDeployed_: boolean;
        success_: boolean;
        revertReason_: string;
      }
    >;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateAuths(
      authsStatus_: AvoForwarderStructs.AddressBoolStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    updateBroadcasters(
      broadcastersStatus_: AvoForwarderStructs.AddressBoolStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    verifyV1(
      from_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      params_: AvocadoMultisigStructs.CastParamsStruct,
      forwardParams_: AvocadoMultisigStructs.CastForwardParamsStruct,
      signaturesParams_: AvocadoMultisigStructs.SignatureParamsStruct[],
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "AuthUpdated(address,bool)"(
      auth?: PromiseOrValue<string> | null,
      status?: PromiseOrValue<boolean> | null
    ): AuthUpdatedEventFilter;
    AuthUpdated(
      auth?: PromiseOrValue<string> | null,
      status?: PromiseOrValue<boolean> | null
    ): AuthUpdatedEventFilter;

    "BroadcasterUpdated(address,bool)"(
      broadcaster?: PromiseOrValue<string> | null,
      status?: PromiseOrValue<boolean> | null
    ): BroadcasterUpdatedEventFilter;
    BroadcasterUpdated(
      broadcaster?: PromiseOrValue<string> | null,
      status?: PromiseOrValue<boolean> | null
    ): BroadcasterUpdatedEventFilter;

    "ExecuteFailed(address,uint32,address,address,bytes,string)"(
      avocadoOwner?: PromiseOrValue<string> | null,
      index?: null,
      avocadoAddress?: PromiseOrValue<string> | null,
      source?: PromiseOrValue<string> | null,
      metadata?: null,
      reason?: null
    ): ExecuteFailedEventFilter;
    ExecuteFailed(
      avocadoOwner?: PromiseOrValue<string> | null,
      index?: null,
      avocadoAddress?: PromiseOrValue<string> | null,
      source?: PromiseOrValue<string> | null,
      metadata?: null,
      reason?: null
    ): ExecuteFailedEventFilter;

    "Executed(address,uint32,address,address,bytes)"(
      avocadoOwner?: PromiseOrValue<string> | null,
      index?: null,
      avocadoAddress?: PromiseOrValue<string> | null,
      source?: PromiseOrValue<string> | null,
      metadata?: null
    ): ExecutedEventFilter;
    Executed(
      avocadoOwner?: PromiseOrValue<string> | null,
      index?: null,
      avocadoAddress?: PromiseOrValue<string> | null,
      source?: PromiseOrValue<string> | null,
      metadata?: null
    ): ExecutedEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    avoFactory(overrides?: CallOverrides): Promise<BigNumber>;

    avoNonce(
      owner_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    avocadoBytecode(overrides?: CallOverrides): Promise<BigNumber>;

    avocadoVersion(
      owner_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    avocadoVersionName(
      owner_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    computeAvocado(
      owner_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    executeV1(
      from_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      params_: AvocadoMultisigStructs.CastParamsStruct,
      forwardParams_: AvocadoMultisigStructs.CastForwardParamsStruct,
      signaturesParams_: AvocadoMultisigStructs.SignatureParamsStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initialize(
      owner_: PromiseOrValue<string>,
      allowedBroadcasters_: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isAuth(
      auth_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isBroadcaster(
      broadcaster_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<BigNumber>;

    simulateV1(
      from_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      params_: AvocadoMultisigStructs.CastParamsStruct,
      forwardParams_: AvocadoMultisigStructs.CastForwardParamsStruct,
      signaturesParams_: AvocadoMultisigStructs.SignatureParamsStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateAuths(
      authsStatus_: AvoForwarderStructs.AddressBoolStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateBroadcasters(
      broadcastersStatus_: AvoForwarderStructs.AddressBoolStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    verifyV1(
      from_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      params_: AvocadoMultisigStructs.CastParamsStruct,
      forwardParams_: AvocadoMultisigStructs.CastForwardParamsStruct,
      signaturesParams_: AvocadoMultisigStructs.SignatureParamsStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    avoFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    avoNonce(
      owner_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    avocadoBytecode(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    avocadoVersion(
      owner_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    avocadoVersionName(
      owner_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    computeAvocado(
      owner_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    executeV1(
      from_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      params_: AvocadoMultisigStructs.CastParamsStruct,
      forwardParams_: AvocadoMultisigStructs.CastForwardParamsStruct,
      signaturesParams_: AvocadoMultisigStructs.SignatureParamsStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      owner_: PromiseOrValue<string>,
      allowedBroadcasters_: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isAuth(
      auth_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isBroadcaster(
      broadcaster_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    simulateV1(
      from_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      params_: AvocadoMultisigStructs.CastParamsStruct,
      forwardParams_: AvocadoMultisigStructs.CastForwardParamsStruct,
      signaturesParams_: AvocadoMultisigStructs.SignatureParamsStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateAuths(
      authsStatus_: AvoForwarderStructs.AddressBoolStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateBroadcasters(
      broadcastersStatus_: AvoForwarderStructs.AddressBoolStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    verifyV1(
      from_: PromiseOrValue<string>,
      index_: PromiseOrValue<BigNumberish>,
      params_: AvocadoMultisigStructs.CastParamsStruct,
      forwardParams_: AvocadoMultisigStructs.CastForwardParamsStruct,
      signaturesParams_: AvocadoMultisigStructs.SignatureParamsStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
