name: Open PR develop -> master

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  create_pull_request:
    if: github.event.pull_request.merged == true
    name: Create Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Create Pull Request
        run: gh pr create -B master -H develop --title "Staging"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
