name: Open PR develop -> master

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  create_pull_request:
    if: github.event.pull_request.merged == true
    name: Create Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.4
        with:
          branch: develop
          base: master
          title: Staging Changes

